services:
  postgres:
     container_name: postgres-sql-bsn
     image: postgres
     environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: Vashisth123
       PGDATA: /var/lib/postgresql/data
       POSTGRES_DB: online_platform_newnetwork
     volumes:
       - postgres:/data/postgres
     ports:
       - 5432-5432
     networks:
       - spring-demo
     restart: unless-stopped
  mail-dev:
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
networks:
  spring-demo:
    driver: bridge
volumes:
  postgres:
    driver: local

